version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  deploy:
    executor: node/default
    steps:
      - run: npm run deploy

workflows:
  test_my_app_then_deploy:
    jobs:
      - node/test
      - deploy
