version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: npm run deploy

workflows:
  test_and_build:
    jobs:
      - node/test
      - deploy:
          requires:
            - node/test
          filters:
            branches:
              only: main
