version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: sudo npm install -g npm@latest
      - run: npm run test

workflows:
  test_my_app:
    jobs:
      - test
      - run:
          command: npm run deploy
          name: Deploy to GHPages
